### ISSUE TITLE
SyntaxError: only named arguments may follow *expression

### ISSUE THREAD

**Issue by liampaull** [duckietown/challenge-aido1_LF1-baseline-IL-sim-tensorflow#1]
```
lpaull:challenge-aido1_LF1-baseline-IL-sim-tensorflow$ python ./log.py 
Traceback (most recent call last):
  File "./log.py", line 2, in <module>
    from gym_duckietown.envs import DuckietownEnv
  File "/home/lpaull/gym-duckietown/gym_duckietown/envs/__init__.py", line 2, in <module>
    from gym_duckietown.envs.simplesim_env import SimpleSimEnv
  File "/home/lpaull/gym-duckietown/gym_duckietown/envs/simplesim_env.py", line 515
    glClearColor(*self.horizonColor, 1.0)
SyntaxError: only named arguments may follow *expression
```

**Comment by liampaull** [comment]
updated requirements fixed
