### ISSUE TITLE
"log.py" throws TypeError

### ISSUE THREAD

**Issue by rizavelioglu** [duckietown/challenge-aido1_LF1-baseline-IL-sim-tensorflow#7]
After a few seconds running "python log.py" I get the following an error:

Traceback (most recent call last):
 File "log.py", line 26, in <module>
   action = expert.predict(None)
 File "/challenge-aido_LF-baseline-IL-sim-tensorflow-v2/learning/teacher.py", line 29, in predict
   follow_point = closest_point + closest_tangent * lookup_distance
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

**Comment by liampaull** [comment]
@plafer have you tried this baseline recently? Did you experience this error?

**Comment by plafer** [comment]
I didn't but I can try it to see if I get any error

**Comment by plafer** [comment]
Also we keep putting `pip3 install ...`, but conda environments just have `pip` by default, and it points to the python3 version.

**Comment by bhairavmehta95** [comment]
Here's the issue: it was fixed in the normal AIDO simulator:
https://github.com/duckietown/gym-duckietown/blob/master/gym_duckietown/simulator.py#L1037-L1076

But this code seems to short circuit that fix, because it directly gets the point / angle, but doesn't check for None (and then subsequently end the episode)
